<a href="https://colab.research.google.com/github/QuentasiJhonny/IA2/blob/main/Temperaturas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

Mounted at /content/gdrive


In [11]:
import numpy as np
from tensorflow.python.keras import backend as k
k.clear_session()
import numpy as np
import pandas as pd
np.random.seed(10)

from keras.layers import Input, Dense, SimpleRNN
from keras.models import Model
#from keras.optimizers import SGD
#from keras.utils import to_categorical
from keras import backend as K

In [14]:
dataset_train = pd.read_csv("/content/gdrive/MyDrive/datasets/Temperaturas/dataTemperatura.txt")

print(dataset_train.head())

training_set = dataset_train.iloc[:, 0:1].values

print(training_set)

   Tempmínima  \tTempmáxima
0        12.4          24.0
1        14.0          24.5
2        13.8          24.2
3        13.0          21.0
4        10.0          19.2
[[12.4]
 [14. ]
 [13.8]
 [13. ]
 [10. ]
 [12. ]
 [11.8]
 [11.6]
 [10. ]
 [13. ]
 [13. ]
 [12.8]
 [13. ]
 [12.8]
 [13. ]
 [12.8]
 [13. ]
 [ 8.8]
 [ 9. ]
 [11.2]
 [10. ]
 [ 8.8]
 [ 9. ]
 [11.2]
 [10. ]
 [11.2]
 [13.5]
 [ 8.8]
 [ 9. ]
 [11.2]
 [10. ]
 [ 8.8]
 [ 9. ]
 [11.2]
 [10. ]
 [11.5]
 [12. ]
 [11.8]
 [12. ]
 [13. ]
 [11.5]
 [12. ]
 [11.8]
 [12. ]
 [13. ]
 [13. ]
 [11. ]
 [11.8]
 [11.5]
 [11.4]
 [10.8]
 [12. ]
 [12.2]
 [11.2]
 [14.5]
 [14.2]
 [11.5]
 [11. ]
 [10. ]
 [10. ]
 [11.5]
 [11. ]
 [10. ]
 [10. ]
 [11.5]
 [11. ]
 [10. ]
 [10. ]
 [10.2]
 [ 9. ]
 [10. ]
 [14. ]
 [12. ]
 [11.5]
 [12. ]
 [12.8]
 [11.5]
 [11.8]
 [11.8]
 [14. ]
 [12. ]
 [11.5]
 [12. ]
 [12.8]
 [14. ]
 [12. ]
 [11.5]
 [12. ]
 [12.8]
 [10.5]
 [11.5]
 [14. ]
 [12. ]
 [11.5]
 [12. ]
 [12.8]
 [12.8]
 [12.5]
 [14.5]
 [14. ]
 [12.5]
 [12.2]
 [12.4]
 [11. ]


In [30]:
#normalizacion de los datos usando el metodo MinmaxScaler 
from sklearn.preprocessing import MinMaxScaler

sc = MinMaxScaler(feature_range = (0, 1))
training_set_scaled = sc.fit_transform(training_set)


X_train, y_train = [], []
for i in range(30, len(training_set_scaled)):
    X_train.append(training_set_scaled[i - 30: i, 0])
    y_train.append(training_set_scaled[i])

X_train, y_train = np.array(X_train), np.array(y_train)

print(f'Forma de x: {X_train.shape}')
print(f'Forma de y: {y_train.shape}')

y_train

Forma de x: (263, 30)
Forma de y: (263, 1)


array([[0.40329218],
       [0.35390947],
       [0.36213992],
       [0.4526749 ],
       [0.40329218],
       [0.46502058],
       [0.48559671],
       [0.47736626],
       [0.48559671],
       [0.52674897],
       [0.46502058],
       [0.48559671],
       [0.47736626],
       [0.48559671],
       [0.52674897],
       [0.52674897],
       [0.44444444],
       [0.47736626],
       [0.46502058],
       [0.46090535],
       [0.43621399],
       [0.48559671],
       [0.49382716],
       [0.4526749 ],
       [0.58847737],
       [0.57613169],
       [0.46502058],
       [0.44444444],
       [0.40329218],
       [0.40329218],
       [0.46502058],
       [0.44444444],
       [0.40329218],
       [0.40329218],
       [0.46502058],
       [0.44444444],
       [0.40329218],
       [0.40329218],
       [0.41152263],
       [0.36213992],
       [0.40329218],
       [0.56790123],
       [0.48559671],
       [0.46502058],
       [0.48559671],
       [0.51851852],
       [0.46502058],
       [0.477

In [29]:
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
print(X_train)

[[[0.50205761]
  [0.56790123]
  [0.55967078]
  ...
  [0.47736626]
  [0.46502058]
  [0.46090535]]

 [[0.56790123]
  [0.55967078]
  [0.52674897]
  ...
  [0.46502058]
  [0.46090535]
  [0.43621399]]

 [[0.55967078]
  [0.52674897]
  [0.40329218]
  ...
  [0.46090535]
  [0.43621399]
  [0.48559671]]

 ...

 [[0.38271605]
  [0.41152263]
  [0.40329218]
  ...
  [0.58847737]
  [0.40329218]
  [1.        ]]

 [[0.41152263]
  [0.40329218]
  [0.40329218]
  ...
  [0.40329218]
  [1.        ]
  [0.46502058]]

 [[0.40329218]
  [0.40329218]
  [0.42798354]
  ...
  [1.        ]
  [0.46502058]
  [0.32921811]]]


In [17]:
#entrenamiento del modelo


from keras.models import Sequential
from keras.layers import Dense, Dropout, LSTM

modelo = Sequential()
modelo.add(LSTM(40,return_sequences = True, input_shape = (X_train.shape[1], 1)))
modelo.add(Dropout(.2))
modelo.add(LSTM(40, return_sequences = True))
modelo.add(Dropout(.2))
modelo.add(LSTM(40, return_sequences = False))
modelo.add(Dense(1))
modelo.compile(optimizer = 'adam', loss = 'mean_squared_error', metrics = ['accuracy'])

modelo.fit(X_train, y_train, epochs = 300, batch_size = 32)

Epoch 1/300
8/8 [==============================] - 6s 72ms/step - loss: 0.0665 - accuracy: 0.0041
Epoch 2/300
8/8 [==============================] - 1s 80ms/step - loss: 0.0179 - accuracy: 0.0082
Epoch 3/300
8/8 [==============================] - 1s 75ms/step - loss: 0.0153 - accuracy: 0.0041
Epoch 4/300
8/8 [==============================] - 1s 74ms/step - loss: 0.0127 - accuracy: 0.0041
Epoch 5/300
8/8 [==============================] - 1s 75ms/step - loss: 0.0102 - accuracy: 0.0041
Epoch 6/300
8/8 [==============================] - 1s 71ms/step - loss: 0.0103 - accuracy: 0.0041
Epoch 7/300
8/8 [==============================] - 1s 69ms/step - loss: 0.0101 - accuracy: 0.0041
Epoch 8/300
8/8 [==============================] - 1s 74ms/step - loss: 0.0097 - accuracy: 0.0041
Epoch 9/300
8/8 [==============================] - 1s 74ms/step - loss: 0.0096 - accuracy: 0.0041
Epoch 10/300
8/8 [==============================] - 1s 74ms/step - loss: 0.0098 - accuracy: 0.0041
Epoch 11/300
8/8 [=

In [26]:
#Probar precio de Temepratura Minima
dataset_test = pd.read_csv("/content/gdrive/MyDrive/datasets/Temperaturas/dataTemperatura.txt")
real_stock_val = dataset_test.iloc[:,0:1].values
dataset_total = pd.concat((dataset_train['Tempmínima'], dataset_test['Tempmínima']), axis=0)

inputs = dataset_total[len(dataset_total) - len(dataset_test) - 30:].values
inputs = inputs.reshape(-1, 1)
inputs = sc.transform(inputs)
X_test = []
for i in range(30, len(inputs)):
    X_test.append(inputs[i - 30: i])

X_test = np.array(X_test)
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
prediccionTemperaturas = modelo.predict(X_test)
print(prediccionTemperaturas)

[[0.5185624 ]
 [0.54180133]
 [0.5787581 ]
 [0.60402966]
 [0.6023842 ]
 [0.55675167]
 [0.5274041 ]
 [0.50387233]
 [0.4887689 ]
 [0.47359574]
 [0.48542157]
 [0.5039972 ]
 [0.5109815 ]
 [0.51720226]
 [0.52237564]
 [0.527857  ]
 [0.53428   ]
 [0.5412312 ]
 [0.5136853 ]
 [0.49603686]
 [0.50308543]
 [0.500742  ]
 [0.4812196 ]
 [0.45999753]
 [0.45897618]
 [0.45164996]
 [0.44032717]
 [0.47812468]
 [0.44923842]
 [0.41611755]
 [0.4123391 ]
 [0.41289747]
 [0.4078849 ]
 [0.40518203]
 [0.4219384 ]
 [0.42850307]
 [0.4441218 ]
 [0.46097112]
 [0.4709062 ]
 [0.4770585 ]
 [0.48870626]
 [0.48373434]
 [0.48241073]
 [0.4815491 ]
 [0.48561284]
 [0.50201356]
 [0.51895875]
 [0.51682526]
 [0.52374303]
 [0.5279012 ]
 [0.5309211 ]
 [0.5244712 ]
 [0.5206462 ]
 [0.51166505]
 [0.49467847]
 [0.5045587 ]
 [0.517681  ]
 [0.514159  ]
 [0.49956068]
 [0.484833  ]
 [0.4810169 ]
 [0.49321693]
 [0.49996853]
 [0.49348584]
 [0.4855567 ]
 [0.48693702]
 [0.4844408 ]
 [0.47144803]
 [0.4574565 ]
 [0.447476  ]
 [0.43186265]
 [0.42

In [27]:
prediccion=sc.inverse_transform(predicted_stock_prices)


In [28]:
print(prediccion)
len(prediccion)

[[10.492312 ]
 [10.696072 ]
 [11.509218 ]
 [12.046131 ]
 [12.028019 ]
 [11.177276 ]
 [11.284976 ]
 [10.340244 ]
 [10.339156 ]
 [10.267597 ]
 [10.891922 ]
 [11.195753 ]
 [11.170532 ]
 [11.103326 ]
 [11.014655 ]
 [11.181563 ]
 [11.171425 ]
 [11.238343 ]
 [10.46965  ]
 [10.092539 ]
 [10.164443 ]
 [10.069852 ]
 [ 9.715616 ]
 [ 9.396051 ]
 [ 9.594523 ]
 [ 9.487596 ]
 [ 9.548895 ]
 [ 9.994817 ]
 [ 9.576968 ]
 [ 9.208494 ]
 [ 9.30857  ]
 [ 9.301757 ]
 [ 9.1210985]
 [ 9.025556 ]
 [ 9.312757 ]
 [ 9.410068 ]
 [ 9.642457 ]
 [ 9.742628 ]
 [ 9.979791 ]
 [10.165064 ]
 [10.3748665]
 [10.2986765]
 [10.422926 ]
 [10.5405245]
 [10.592107 ]
 [10.953912 ]
 [11.155718 ]
 [10.837895 ]
 [10.768618 ]
 [10.68245  ]
 [10.547469 ]
 [10.431671 ]
 [10.573327 ]
 [10.754273 ]
 [10.641659 ]
 [11.116695 ]
 [11.3687525]
 [11.053032 ]
 [10.65887  ]
 [10.234373 ]
 [ 9.997429 ]
 [10.265344 ]
 [10.365842 ]
 [10.184921 ]
 [10.067054 ]
 [10.017571 ]
 [ 9.869857 ]
 [ 9.651196 ]
 [ 9.479564 ]
 [ 9.465597 ]
 [ 9.243085 ]
 [ 9.1

293