In [1]:
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

Mounted at /content/gdrive


In [2]:
import numpy as np
from tensorflow.python.keras import backend as k
k.clear_session()
import numpy as np
import pandas as pd
np.random.seed(10)

from keras.layers import Input, Dense, SimpleRNN
from keras.models import Model
from keras.optimizers import SGD
from keras.utils import to_categorical
from keras import backend as K

In [3]:
dataset_train = pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/SIS_421/Primer_Parcial/CotizacionDolar/CambioDolar2010-2020.txt")

print(dataset_train.head())

training_set = dataset_train.iloc[:, 0:1].values

print(training_set)

   Venta   Compra
0   7.07     6.97
1   7.07     6.97
2   7.07     6.97
3   7.07     6.97
4   7.07     6.97
[[7.07]
 [7.07]
 [7.07]
 [7.07]
 [7.07]
 [7.07]
 [7.07]
 [7.07]
 [7.07]
 [7.07]
 [7.06]
 [7.06]
 [7.06]
 [7.06]
 [7.06]
 [7.06]
 [7.06]
 [7.05]
 [7.05]
 [7.05]
 [7.05]
 [7.05]
 [7.04]
 [7.04]
 [7.04]
 [7.04]
 [7.03]
 [7.03]
 [7.03]
 [7.03]
 [7.03]
 [7.02]
 [7.02]
 [7.02]
 [7.01]
 [7.01]
 [7.01]
 [7.  ]
 [7.  ]
 [6.99]
 [6.99]
 [6.99]
 [6.99]
 [6.99]
 [6.99]
 [6.99]
 [6.99]
 [6.99]
 [6.99]
 [6.99]
 [6.99]
 [6.99]
 [6.99]
 [6.99]
 [6.98]
 [6.98]
 [6.98]
 [6.98]
 [6.98]
 [6.98]
 [6.98]
 [6.98]
 [6.98]
 [6.98]
 [6.98]
 [6.98]
 [6.98]
 [6.98]
 [6.97]
 [6.97]
 [6.97]
 [6.97]
 [6.97]
 [6.97]
 [6.97]
 [6.97]
 [6.97]
 [6.97]
 [6.97]
 [6.97]
 [6.97]
 [6.96]
 [6.96]
 [6.96]
 [6.96]
 [6.96]
 [6.96]
 [6.96]
 [6.96]
 [6.96]
 [6.96]
 [6.96]
 [6.96]
 [6.96]
 [6.96]
 [6.96]
 [6.96]
 [6.96]
 [6.96]
 [6.96]
 [6.96]
 [6.96]
 [6.96]
 [6.96]
 [6.96]
 [6.96]
 [6.96]
 [6.96]
 [6.96]
 [6.96]
 [6.96]
 [6.

In [4]:
#normalizacion de los datos usando el metodo MinmaxScaler 
from sklearn.preprocessing import MinMaxScaler

sc = MinMaxScaler(feature_range = (0, 1))
training_set_scaled = sc.fit_transform(training_set)


X_train, y_train = [], []
for i in range(50, len(training_set_scaled)):
    X_train.append(training_set_scaled[i - 50: i, 0])
    y_train.append(training_set_scaled[i])

X_train, y_train = np.array(X_train), np.array(y_train)

print(f'Forma de x: {X_train.shape}')
print(f'Forma de y: {y_train.shape}')

y_train

Forma de x: (100, 50)
Forma de y: (100, 1)


array([[0.27272727],
       [0.27272727],
       [0.27272727],
       [0.27272727],
       [0.18181818],
       [0.18181818],
       [0.18181818],
       [0.18181818],
       [0.18181818],
       [0.18181818],
       [0.18181818],
       [0.18181818],
       [0.18181818],
       [0.18181818],
       [0.18181818],
       [0.18181818],
       [0.18181818],
       [0.18181818],
       [0.09090909],
       [0.09090909],
       [0.09090909],
       [0.09090909],
       [0.09090909],
       [0.09090909],
       [0.09090909],
       [0.09090909],
       [0.09090909],
       [0.09090909],
       [0.09090909],
       [0.09090909],
       [0.09090909],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.   

In [5]:
#entrenamiento del modelo
X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))

from keras.models import Sequential
from keras.layers import Dense, Dropout, LSTM

modelo = Sequential()
modelo.add(LSTM(40,return_sequences = True, input_shape = (X_train.shape[1], 1)))
modelo.add(Dropout(.2))
modelo.add(LSTM(40, return_sequences = True))
modelo.add(Dropout(.2))
modelo.add(LSTM(40, return_sequences = False))
modelo.add(Dense(1))
modelo.compile(optimizer = 'adam', loss = 'mean_squared_error', metrics = ['accuracy'])
modelo.fit(X_train, y_train, epochs = 300, batch_size = 32)

Epoch 1/300
4/4 [==============================] - 5s 70ms/step - loss: 0.0052 - accuracy: 0.7072
Epoch 2/300
4/4 [==============================] - 0s 71ms/step - loss: 0.0029 - accuracy: 0.7125
Epoch 3/300
4/4 [==============================] - 0s 73ms/step - loss: 7.9606e-04 - accuracy: 0.6770
Epoch 4/300
4/4 [==============================] - 0s 67ms/step - loss: 0.0012 - accuracy: 0.6875
Epoch 5/300
4/4 [==============================] - 0s 71ms/step - loss: 6.7063e-04 - accuracy: 0.6927
Epoch 6/300
4/4 [==============================] - 0s 72ms/step - loss: 6.9365e-04 - accuracy: 0.6812
Epoch 7/300
4/4 [==============================] - 0s 71ms/step - loss: 6.9582e-04 - accuracy: 0.6885
Epoch 8/300
4/4 [==============================] - 0s 77ms/step - loss: 7.3402e-04 - accuracy: 0.6947
Epoch 9/300
4/4 [==============================] - 0s 71ms/step - loss: 5.3181e-04 - accuracy: 0.6802
Epoch 10/300
4/4 [==============================] - 0s 71ms/step - loss: 8.2341e-04 - accuracy

In [6]:
#Probar precio de venta
dataset_test = pd.read_csv("/content/gdrive/MyDrive/Colab Notebooks/SIS_421/Primer_Parcial/CotizacionDolar/CambioDolar2010-2020.txt")
real_stock_val = dataset_test.iloc[:,0:1].values
dataset_total = pd.concat((dataset_train['Venta'], dataset_test['Venta']), axis=0)

inputs = dataset_total[len(dataset_total) - len(dataset_test) - 50:].values
inputs = inputs.reshape(-1, 1)
inputs = sc.transform(inputs)
X_test = []
for i in range(50, len(inputs)):
    X_test.append(inputs[i - 50: i])

X_test = np.array(X_test)
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
predicted_stock_prices = modelo.predict(X_test)
print(predicted_stock_prices)

[[-6.5030344e-04]
 [-3.3820756e-03]
 [-1.0078615e-02]
 [-2.0298680e-02]
 [-3.2170415e-02]
 [-4.2400315e-02]
 [-4.6096243e-02]
 [-3.6856227e-02]
 [-7.7509899e-03]
 [ 4.6455748e-02]
 [ 1.2671770e-01]
 [ 2.3028328e-01]
 [ 3.5204959e-01]
 [ 4.8651925e-01]
 [ 6.2581748e-01]
 [ 7.5891179e-01]
 [ 8.7477422e-01]
 [ 9.6557438e-01]
 [ 1.0283388e+00]
 [ 1.0639228e+00]
 [ 1.0763884e+00]
 [ 1.0715111e+00]
 [ 1.0551513e+00]
 [ 1.0322727e+00]
 [ 1.0060858e+00]
 [ 9.7804672e-01]
 [ 9.4835842e-01]
 [ 9.1681075e-01]
 [ 8.8298410e-01]
 [ 8.4655035e-01]
 [ 8.0751109e-01]
 [ 7.6630187e-01]
 [ 7.2417051e-01]
 [ 6.8248016e-01]
 [ 6.4249885e-01]
 [ 6.0573399e-01]
 [ 5.7306242e-01]
 [ 5.4473680e-01]
 [ 5.2100235e-01]
 [ 5.0134712e-01]
 [ 4.8524776e-01]
 [ 4.7148988e-01]
 [ 4.5854440e-01]
 [ 4.4490072e-01]
 [ 4.2934602e-01]
 [ 4.1114184e-01]
 [ 3.9008743e-01]
 [ 3.6648139e-01]
 [ 3.4101218e-01]
 [ 3.1461090e-01]
 [ 2.8830153e-01]
 [ 2.6287580e-01]
 [ 2.4056160e-01]
 [ 2.2169811e-01]
 [ 2.0642506e-01]
 [ 1.95094

In [8]:
prediccion=sc.inverse_transform(predicted_stock_prices)


In [9]:
print(prediccion)

[[6.9599285]
 [6.959628 ]
 [6.9588914]
 [6.9577675]
 [6.9564614]
 [6.955336 ]
 [6.9549294]
 [6.955946 ]
 [6.9591475]
 [6.9651103]
 [6.973939 ]
 [6.985331 ]
 [6.998726 ]
 [7.0135174]
 [7.02884  ]
 [7.0434804]
 [7.056225 ]
 [7.0662136]
 [7.073117 ]
 [7.077031 ]
 [7.0784025]
 [7.077866 ]
 [7.076067 ]
 [7.07355  ]
 [7.0706697]
 [7.067585 ]
 [7.064319 ]
 [7.060849 ]
 [7.057128 ]
 [7.0531206]
 [7.048826 ]
 [7.0442934]
 [7.039659 ]
 [7.035073 ]
 [7.030675 ]
 [7.0266304]
 [7.023037 ]
 [7.019921 ]
 [7.01731  ]
 [7.015148 ]
 [7.013377 ]
 [7.0118637]
 [7.01044  ]
 [7.0089393]
 [7.007228 ]
 [7.0052257]
 [7.0029097]
 [7.0003133]
 [6.9975114]
 [6.994607 ]
 [6.991713 ]
 [6.9889164]
 [6.986462 ]
 [6.984387 ]
 [6.982707 ]
 [6.9814606]
 [6.98063  ]
 [6.98015  ]
 [6.979925 ]
 [6.9798446]
 [6.9797983]
 [6.9796653]
 [6.9794   ]
 [6.978967 ]
 [6.9783587]
 [6.977591 ]
 [6.9766994]
 [6.975731 ]
 [6.9746914]
 [6.973703 ]
 [6.9728107]
 [6.972023 ]
 [6.971321 ]
 [6.970625 ]
 [6.9699507]
 [6.9692745]
 [6.968579 ]